// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JTRNSYS.proto

#ifndef PROTOBUF_INCLUDED_JTRNSYS_2eproto
#define PROTOBUF_INCLUDED_JTRNSYS_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_JTRNSYS_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_JTRNSYS_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_JTRNSYS_2eproto();
namespace JavaTRNSYSDataTypes {
class DataTypes;
class DataTypesDefaultTypeInternal;
extern DataTypesDefaultTypeInternal _DataTypes_default_instance_;
class DataTypes_ArrayDataTypes;
class DataTypes_ArrayDataTypesDefaultTypeInternal;
extern DataTypes_ArrayDataTypesDefaultTypeInternal _DataTypes_ArrayDataTypes_default_instance_;
class JTRNSYSData;
class JTRNSYSDataDefaultTypeInternal;
extern JTRNSYSDataDefaultTypeInternal _JTRNSYSData_default_instance_;
}  // namespace JavaTRNSYSDataTypes
namespace google {
namespace protobuf {
template<> ::JavaTRNSYSDataTypes::DataTypes* Arena::CreateMaybeMessage<::JavaTRNSYSDataTypes::DataTypes>(Arena*);
template<> ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes* Arena::CreateMaybeMessage<::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes>(Arena*);
template<> ::JavaTRNSYSDataTypes::JTRNSYSData* Arena::CreateMaybeMessage<::JavaTRNSYSDataTypes::JTRNSYSData>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace JavaTRNSYSDataTypes {

// ===================================================================

class DataTypes_ArrayDataTypes final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JavaTRNSYSDataTypes.DataTypes.ArrayDataTypes) */ {
 public:
  DataTypes_ArrayDataTypes();
  virtual ~DataTypes_ArrayDataTypes();

  DataTypes_ArrayDataTypes(const DataTypes_ArrayDataTypes& from);

  inline DataTypes_ArrayDataTypes& operator=(const DataTypes_ArrayDataTypes& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DataTypes_ArrayDataTypes(DataTypes_ArrayDataTypes&& from) noexcept
    : DataTypes_ArrayDataTypes() {
    *this = ::std::move(from);
  }

  inline DataTypes_ArrayDataTypes& operator=(DataTypes_ArrayDataTypes&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DataTypes_ArrayDataTypes& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DataTypes_ArrayDataTypes* internal_default_instance() {
    return reinterpret_cast<const DataTypes_ArrayDataTypes*>(
               &_DataTypes_ArrayDataTypes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(DataTypes_ArrayDataTypes* other);
  friend void swap(DataTypes_ArrayDataTypes& a, DataTypes_ArrayDataTypes& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DataTypes_ArrayDataTypes* New() const final {
    return CreateMaybeMessage<DataTypes_ArrayDataTypes>(nullptr);
  }

  DataTypes_ArrayDataTypes* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DataTypes_ArrayDataTypes>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DataTypes_ArrayDataTypes& from);
  void MergeFrom(const DataTypes_ArrayDataTypes& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataTypes_ArrayDataTypes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double doubleArray = 1;
  void clear_doublearray();
  static const int kDoubleArrayFieldNumber = 1;
  double doublearray() const;
  void set_doublearray(double value);

  // int32 intArray = 2;
  void clear_intarray();
  static const int kIntArrayFieldNumber = 2;
  ::google::protobuf::int32 intarray() const;
  void set_intarray(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:JavaTRNSYSDataTypes.DataTypes.ArrayDataTypes)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double doublearray_;
  ::google::protobuf::int32 intarray_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_JTRNSYS_2eproto;
};
// -------------------------------------------------------------------

class DataTypes final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JavaTRNSYSDataTypes.DataTypes) */ {
 public:
  DataTypes();
  virtual ~DataTypes();

  DataTypes(const DataTypes& from);

  inline DataTypes& operator=(const DataTypes& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DataTypes(DataTypes&& from) noexcept
    : DataTypes() {
    *this = ::std::move(from);
  }

  inline DataTypes& operator=(DataTypes&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const DataTypes& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DataTypes* internal_default_instance() {
    return reinterpret_cast<const DataTypes*>(
               &_DataTypes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(DataTypes* other);
  friend void swap(DataTypes& a, DataTypes& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DataTypes* New() const final {
    return CreateMaybeMessage<DataTypes>(nullptr);
  }

  DataTypes* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DataTypes>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DataTypes& from);
  void MergeFrom(const DataTypes& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataTypes* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef DataTypes_ArrayDataTypes ArrayDataTypes;

  // accessors -------------------------------------------------------

  // repeated .JavaTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;
  int arrays_size() const;
  void clear_arrays();
  static const int kArraysFieldNumber = 4;
  ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes* mutable_arrays(int index);
  ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes >*
      mutable_arrays();
  const ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes& arrays(int index) const;
  ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes* add_arrays();
  const ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes >&
      arrays() const;

  // string stringData = 1;
  void clear_stringdata();
  static const int kStringDataFieldNumber = 1;
  const ::std::string& stringdata() const;
  void set_stringdata(const ::std::string& value);
  #if LANG_CXX11
  void set_stringdata(::std::string&& value);
  #endif
  void set_stringdata(const char* value);
  void set_stringdata(const char* value, size_t size);
  ::std::string* mutable_stringdata();
  ::std::string* release_stringdata();
  void set_allocated_stringdata(::std::string* stringdata);

  // double doubleData = 3;
  void clear_doubledata();
  static const int kDoubleDataFieldNumber = 3;
  double doubledata() const;
  void set_doubledata(double value);

  // int32 intData = 2;
  void clear_intdata();
  static const int kIntDataFieldNumber = 2;
  ::google::protobuf::int32 intdata() const;
  void set_intdata(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:JavaTRNSYSDataTypes.DataTypes)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes > arrays_;
  ::google::protobuf::internal::ArenaStringPtr stringdata_;
  double doubledata_;
  ::google::protobuf::int32 intdata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_JTRNSYS_2eproto;
};
// -------------------------------------------------------------------

class JTRNSYSData final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:JavaTRNSYSDataTypes.JTRNSYSData) */ {
 public:
  JTRNSYSData();
  virtual ~JTRNSYSData();

  JTRNSYSData(const JTRNSYSData& from);

  inline JTRNSYSData& operator=(const JTRNSYSData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JTRNSYSData(JTRNSYSData&& from) noexcept
    : JTRNSYSData() {
    *this = ::std::move(from);
  }

  inline JTRNSYSData& operator=(JTRNSYSData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const JTRNSYSData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JTRNSYSData* internal_default_instance() {
    return reinterpret_cast<const JTRNSYSData*>(
               &_JTRNSYSData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(JTRNSYSData* other);
  friend void swap(JTRNSYSData& a, JTRNSYSData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JTRNSYSData* New() const final {
    return CreateMaybeMessage<JTRNSYSData>(nullptr);
  }

  JTRNSYSData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<JTRNSYSData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const JTRNSYSData& from);
  void MergeFrom(const JTRNSYSData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JTRNSYSData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .JavaTRNSYSDataTypes.DataTypes data = 1;
  int data_size() const;
  void clear_data();
  static const int kDataFieldNumber = 1;
  ::JavaTRNSYSDataTypes::DataTypes* mutable_data(int index);
  ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes >*
      mutable_data();
  const ::JavaTRNSYSDataTypes::DataTypes& data(int index) const;
  ::JavaTRNSYSDataTypes::DataTypes* add_data();
  const ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes >&
      data() const;

  // @@protoc_insertion_point(class_scope:JavaTRNSYSDataTypes.JTRNSYSData)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes > data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_JTRNSYS_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DataTypes_ArrayDataTypes

// double doubleArray = 1;
inline void DataTypes_ArrayDataTypes::clear_doublearray() {
  doublearray_ = 0;
}
inline double DataTypes_ArrayDataTypes::doublearray() const {
  // @@protoc_insertion_point(field_get:JavaTRNSYSDataTypes.DataTypes.ArrayDataTypes.doubleArray)
  return doublearray_;
}
inline void DataTypes_ArrayDataTypes::set_doublearray(double value) {
  
  doublearray_ = value;
  // @@protoc_insertion_point(field_set:JavaTRNSYSDataTypes.DataTypes.ArrayDataTypes.doubleArray)
}

// int32 intArray = 2;
inline void DataTypes_ArrayDataTypes::clear_intarray() {
  intarray_ = 0;
}
inline ::google::protobuf::int32 DataTypes_ArrayDataTypes::intarray() const {
  // @@protoc_insertion_point(field_get:JavaTRNSYSDataTypes.DataTypes.ArrayDataTypes.intArray)
  return intarray_;
}
inline void DataTypes_ArrayDataTypes::set_intarray(::google::protobuf::int32 value) {
  
  intarray_ = value;
  // @@protoc_insertion_point(field_set:JavaTRNSYSDataTypes.DataTypes.ArrayDataTypes.intArray)
}

// -------------------------------------------------------------------

// DataTypes

// string stringData = 1;
inline void DataTypes::clear_stringdata() {
  stringdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DataTypes::stringdata() const {
  // @@protoc_insertion_point(field_get:JavaTRNSYSDataTypes.DataTypes.stringData)
  return stringdata_.GetNoArena();
}
inline void DataTypes::set_stringdata(const ::std::string& value) {
  
  stringdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:JavaTRNSYSDataTypes.DataTypes.stringData)
}
#if LANG_CXX11
inline void DataTypes::set_stringdata(::std::string&& value) {
  
  stringdata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:JavaTRNSYSDataTypes.DataTypes.stringData)
}
#endif
inline void DataTypes::set_stringdata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  stringdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:JavaTRNSYSDataTypes.DataTypes.stringData)
}
inline void DataTypes::set_stringdata(const char* value, size_t size) {
  
  stringdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:JavaTRNSYSDataTypes.DataTypes.stringData)
}
inline ::std::string* DataTypes::mutable_stringdata() {
  
  // @@protoc_insertion_point(field_mutable:JavaTRNSYSDataTypes.DataTypes.stringData)
  return stringdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DataTypes::release_stringdata() {
  // @@protoc_insertion_point(field_release:JavaTRNSYSDataTypes.DataTypes.stringData)
  
  return stringdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DataTypes::set_allocated_stringdata(::std::string* stringdata) {
  if (stringdata != nullptr) {
    
  } else {
    
  }
  stringdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), stringdata);
  // @@protoc_insertion_point(field_set_allocated:JavaTRNSYSDataTypes.DataTypes.stringData)
}

// int32 intData = 2;
inline void DataTypes::clear_intdata() {
  intdata_ = 0;
}
inline ::google::protobuf::int32 DataTypes::intdata() const {
  // @@protoc_insertion_point(field_get:JavaTRNSYSDataTypes.DataTypes.intData)
  return intdata_;
}
inline void DataTypes::set_intdata(::google::protobuf::int32 value) {
  
  intdata_ = value;
  // @@protoc_insertion_point(field_set:JavaTRNSYSDataTypes.DataTypes.intData)
}

// double doubleData = 3;
inline void DataTypes::clear_doubledata() {
  doubledata_ = 0;
}
inline double DataTypes::doubledata() const {
  // @@protoc_insertion_point(field_get:JavaTRNSYSDataTypes.DataTypes.doubleData)
  return doubledata_;
}
inline void DataTypes::set_doubledata(double value) {
  
  doubledata_ = value;
  // @@protoc_insertion_point(field_set:JavaTRNSYSDataTypes.DataTypes.doubleData)
}

// repeated .JavaTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;
inline int DataTypes::arrays_size() const {
  return arrays_.size();
}
inline void DataTypes::clear_arrays() {
  arrays_.Clear();
}
inline ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes* DataTypes::mutable_arrays(int index) {
  // @@protoc_insertion_point(field_mutable:JavaTRNSYSDataTypes.DataTypes.arrays)
  return arrays_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes >*
DataTypes::mutable_arrays() {
  // @@protoc_insertion_point(field_mutable_list:JavaTRNSYSDataTypes.DataTypes.arrays)
  return &arrays_;
}
inline const ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes& DataTypes::arrays(int index) const {
  // @@protoc_insertion_point(field_get:JavaTRNSYSDataTypes.DataTypes.arrays)
  return arrays_.Get(index);
}
inline ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes* DataTypes::add_arrays() {
  // @@protoc_insertion_point(field_add:JavaTRNSYSDataTypes.DataTypes.arrays)
  return arrays_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes_ArrayDataTypes >&
DataTypes::arrays() const {
  // @@protoc_insertion_point(field_list:JavaTRNSYSDataTypes.DataTypes.arrays)
  return arrays_;
}

// -------------------------------------------------------------------

// JTRNSYSData

// repeated .JavaTRNSYSDataTypes.DataTypes data = 1;
inline int JTRNSYSData::data_size() const {
  return data_.size();
}
inline void JTRNSYSData::clear_data() {
  data_.Clear();
}
inline ::JavaTRNSYSDataTypes::DataTypes* JTRNSYSData::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:JavaTRNSYSDataTypes.JTRNSYSData.data)
  return data_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes >*
JTRNSYSData::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:JavaTRNSYSDataTypes.JTRNSYSData.data)
  return &data_;
}
inline const ::JavaTRNSYSDataTypes::DataTypes& JTRNSYSData::data(int index) const {
  // @@protoc_insertion_point(field_get:JavaTRNSYSDataTypes.JTRNSYSData.data)
  return data_.Get(index);
}
inline ::JavaTRNSYSDataTypes::DataTypes* JTRNSYSData::add_data() {
  // @@protoc_insertion_point(field_add:JavaTRNSYSDataTypes.JTRNSYSData.data)
  return data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::JavaTRNSYSDataTypes::DataTypes >&
JTRNSYSData::data() const {
  // @@protoc_insertion_point(field_list:JavaTRNSYSDataTypes.JTRNSYSData.data)
  return data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace JavaTRNSYSDataTypes

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_JTRNSYS_2eproto
