// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JTRNSYSMessage.proto

#include "JTRNSYSMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_JTRNSYSMessage_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_DataTypes_ArrayDataTypes_JTRNSYSMessage_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_JTRNSYSMessage_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_DataTypes_JTRNSYSMessage_2eproto;
namespace JTRNSYSDataTypes {
class DataTypes_ArrayDataTypesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DataTypes_ArrayDataTypes> _instance;
} _DataTypes_ArrayDataTypes_default_instance_;
class DataTypesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DataTypes> _instance;
} _DataTypes_default_instance_;
class JTRNSYSDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<JTRNSYSData> _instance;
} _JTRNSYSData_default_instance_;
}  // namespace JTRNSYSDataTypes
static void InitDefaultsDataTypes_ArrayDataTypes_JTRNSYSMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::JTRNSYSDataTypes::_DataTypes_ArrayDataTypes_default_instance_;
    new (ptr) ::JTRNSYSDataTypes::DataTypes_ArrayDataTypes();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::JTRNSYSDataTypes::DataTypes_ArrayDataTypes::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_DataTypes_ArrayDataTypes_JTRNSYSMessage_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDataTypes_ArrayDataTypes_JTRNSYSMessage_2eproto}, {}};

static void InitDefaultsDataTypes_JTRNSYSMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::JTRNSYSDataTypes::_DataTypes_default_instance_;
    new (ptr) ::JTRNSYSDataTypes::DataTypes();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::JTRNSYSDataTypes::DataTypes::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_DataTypes_JTRNSYSMessage_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsDataTypes_JTRNSYSMessage_2eproto}, {
      &scc_info_DataTypes_ArrayDataTypes_JTRNSYSMessage_2eproto.base,}};

static void InitDefaultsJTRNSYSData_JTRNSYSMessage_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::JTRNSYSDataTypes::_JTRNSYSData_default_instance_;
    new (ptr) ::JTRNSYSDataTypes::JTRNSYSData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::JTRNSYSDataTypes::JTRNSYSData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_JTRNSYSData_JTRNSYSMessage_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsJTRNSYSData_JTRNSYSMessage_2eproto}, {
      &scc_info_DataTypes_JTRNSYSMessage_2eproto.base,}};

void InitDefaults_JTRNSYSMessage_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_DataTypes_ArrayDataTypes_JTRNSYSMessage_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DataTypes_JTRNSYSMessage_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_JTRNSYSData_JTRNSYSMessage_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_JTRNSYSMessage_2eproto[3];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_JTRNSYSMessage_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_JTRNSYSMessage_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_JTRNSYSMessage_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes_ArrayDataTypes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes_ArrayDataTypes, doublearray_),
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes_ArrayDataTypes, intarray_),
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes_ArrayDataTypes, stringarray_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes, stringdata_),
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes, intdata_),
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes, doubledata_),
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::DataTypes, arrays_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::JTRNSYSData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::JTRNSYSDataTypes::JTRNSYSData, data_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::JTRNSYSDataTypes::DataTypes_ArrayDataTypes)},
  { 8, -1, sizeof(::JTRNSYSDataTypes::DataTypes)},
  { 17, -1, sizeof(::JTRNSYSDataTypes::JTRNSYSData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::JTRNSYSDataTypes::_DataTypes_ArrayDataTypes_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::JTRNSYSDataTypes::_DataTypes_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::JTRNSYSDataTypes::_JTRNSYSData_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_JTRNSYSMessage_2eproto = {
  {}, AddDescriptors_JTRNSYSMessage_2eproto, "JTRNSYSMessage.proto", schemas,
  file_default_instances, TableStruct_JTRNSYSMessage_2eproto::offsets,
  file_level_metadata_JTRNSYSMessage_2eproto, 3, file_level_enum_descriptors_JTRNSYSMessage_2eproto, file_level_service_descriptors_JTRNSYSMessage_2eproto,
};

const char descriptor_table_protodef_JTRNSYSMessage_2eproto[] =
  "\n\024JTRNSYSMessage.proto\022\020JTRNSYSDataTypes"
  "\"\316\001\n\tDataTypes\022\022\n\nstringData\030\001 \001(\t\022\017\n\007in"
  "tData\030\002 \001(\005\022\022\n\ndoubleData\030\003 \001(\001\022:\n\006array"
  "s\030\004 \003(\0132*.JTRNSYSDataTypes.DataTypes.Arr"
  "ayDataTypes\032L\n\016ArrayDataTypes\022\023\n\013doubleA"
  "rray\030\001 \001(\001\022\020\n\010intArray\030\002 \001(\005\022\023\n\013stringAr"
  "ray\030\003 \001(\t\"8\n\013JTRNSYSData\022)\n\004data\030\001 \003(\0132\033"
  ".JTRNSYSDataTypes.DataTypesB\032\n\ncom.socke"
  "tB\014JTRNSYSProtob\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_JTRNSYSMessage_2eproto = {
  false, InitDefaults_JTRNSYSMessage_2eproto, 
  descriptor_table_protodef_JTRNSYSMessage_2eproto,
  "JTRNSYSMessage.proto", &assign_descriptors_table_JTRNSYSMessage_2eproto, 343,
};

void AddDescriptors_JTRNSYSMessage_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_JTRNSYSMessage_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_JTRNSYSMessage_2eproto = []() { AddDescriptors_JTRNSYSMessage_2eproto(); return true; }();
namespace JTRNSYSDataTypes {

// ===================================================================

void DataTypes_ArrayDataTypes::InitAsDefaultInstance() {
}
class DataTypes_ArrayDataTypes::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DataTypes_ArrayDataTypes::kDoubleArrayFieldNumber;
const int DataTypes_ArrayDataTypes::kIntArrayFieldNumber;
const int DataTypes_ArrayDataTypes::kStringArrayFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DataTypes_ArrayDataTypes::DataTypes_ArrayDataTypes()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
}
DataTypes_ArrayDataTypes::DataTypes_ArrayDataTypes(const DataTypes_ArrayDataTypes& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  stringarray_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stringarray().size() > 0) {
    stringarray_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringarray_);
  }
  ::memcpy(&doublearray_, &from.doublearray_,
    static_cast<size_t>(reinterpret_cast<char*>(&intarray_) -
    reinterpret_cast<char*>(&doublearray_)) + sizeof(intarray_));
  // @@protoc_insertion_point(copy_constructor:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
}

void DataTypes_ArrayDataTypes::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_DataTypes_ArrayDataTypes_JTRNSYSMessage_2eproto.base);
  stringarray_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&doublearray_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&intarray_) -
      reinterpret_cast<char*>(&doublearray_)) + sizeof(intarray_));
}

DataTypes_ArrayDataTypes::~DataTypes_ArrayDataTypes() {
  // @@protoc_insertion_point(destructor:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  SharedDtor();
}

void DataTypes_ArrayDataTypes::SharedDtor() {
  stringarray_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DataTypes_ArrayDataTypes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DataTypes_ArrayDataTypes& DataTypes_ArrayDataTypes::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_DataTypes_ArrayDataTypes_JTRNSYSMessage_2eproto.base);
  return *internal_default_instance();
}


void DataTypes_ArrayDataTypes::Clear() {
// @@protoc_insertion_point(message_clear_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  stringarray_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&doublearray_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&intarray_) -
      reinterpret_cast<char*>(&doublearray_)) + sizeof(intarray_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DataTypes_ArrayDataTypes::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<DataTypes_ArrayDataTypes*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // double doubleArray = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 9) goto handle_unusual;
        msg->set_doublearray(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // int32 intArray = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_intarray(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string stringArray = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("JTRNSYSDataTypes.DataTypes.ArrayDataTypes.stringArray");
        object = msg->mutable_stringarray();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DataTypes_ArrayDataTypes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double doubleArray = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (9 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &doublearray_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 intArray = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intarray_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string stringArray = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringarray()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stringarray().data(), static_cast<int>(this->stringarray().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "JTRNSYSDataTypes.DataTypes.ArrayDataTypes.stringArray"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DataTypes_ArrayDataTypes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double doubleArray = 1;
  if (this->doublearray() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->doublearray(), output);
  }

  // int32 intArray = 2;
  if (this->intarray() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->intarray(), output);
  }

  // string stringArray = 3;
  if (this->stringarray().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringarray().data(), static_cast<int>(this->stringarray().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "JTRNSYSDataTypes.DataTypes.ArrayDataTypes.stringArray");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->stringarray(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
}

::google::protobuf::uint8* DataTypes_ArrayDataTypes::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double doubleArray = 1;
  if (this->doublearray() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->doublearray(), target);
  }

  // int32 intArray = 2;
  if (this->intarray() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->intarray(), target);
  }

  // string stringArray = 3;
  if (this->stringarray().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringarray().data(), static_cast<int>(this->stringarray().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "JTRNSYSDataTypes.DataTypes.ArrayDataTypes.stringArray");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->stringarray(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  return target;
}

size_t DataTypes_ArrayDataTypes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string stringArray = 3;
  if (this->stringarray().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stringarray());
  }

  // double doubleArray = 1;
  if (this->doublearray() != 0) {
    total_size += 1 + 8;
  }

  // int32 intArray = 2;
  if (this->intarray() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->intarray());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DataTypes_ArrayDataTypes::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  GOOGLE_DCHECK_NE(&from, this);
  const DataTypes_ArrayDataTypes* source =
      ::google::protobuf::DynamicCastToGenerated<DataTypes_ArrayDataTypes>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
    MergeFrom(*source);
  }
}

void DataTypes_ArrayDataTypes::MergeFrom(const DataTypes_ArrayDataTypes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.stringarray().size() > 0) {

    stringarray_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringarray_);
  }
  if (from.doublearray() != 0) {
    set_doublearray(from.doublearray());
  }
  if (from.intarray() != 0) {
    set_intarray(from.intarray());
  }
}

void DataTypes_ArrayDataTypes::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DataTypes_ArrayDataTypes::CopyFrom(const DataTypes_ArrayDataTypes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataTypes_ArrayDataTypes::IsInitialized() const {
  return true;
}

void DataTypes_ArrayDataTypes::Swap(DataTypes_ArrayDataTypes* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DataTypes_ArrayDataTypes::InternalSwap(DataTypes_ArrayDataTypes* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  stringarray_.Swap(&other->stringarray_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(doublearray_, other->doublearray_);
  swap(intarray_, other->intarray_);
}

::google::protobuf::Metadata DataTypes_ArrayDataTypes::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_JTRNSYSMessage_2eproto);
  return ::file_level_metadata_JTRNSYSMessage_2eproto[kIndexInFileMessages];
}


// ===================================================================

void DataTypes::InitAsDefaultInstance() {
}
class DataTypes::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DataTypes::kStringDataFieldNumber;
const int DataTypes::kIntDataFieldNumber;
const int DataTypes::kDoubleDataFieldNumber;
const int DataTypes::kArraysFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DataTypes::DataTypes()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:JTRNSYSDataTypes.DataTypes)
}
DataTypes::DataTypes(const DataTypes& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      arrays_(from.arrays_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  stringdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.stringdata().size() > 0) {
    stringdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringdata_);
  }
  ::memcpy(&doubledata_, &from.doubledata_,
    static_cast<size_t>(reinterpret_cast<char*>(&intdata_) -
    reinterpret_cast<char*>(&doubledata_)) + sizeof(intdata_));
  // @@protoc_insertion_point(copy_constructor:JTRNSYSDataTypes.DataTypes)
}

void DataTypes::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_DataTypes_JTRNSYSMessage_2eproto.base);
  stringdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&doubledata_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&intdata_) -
      reinterpret_cast<char*>(&doubledata_)) + sizeof(intdata_));
}

DataTypes::~DataTypes() {
  // @@protoc_insertion_point(destructor:JTRNSYSDataTypes.DataTypes)
  SharedDtor();
}

void DataTypes::SharedDtor() {
  stringdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DataTypes::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const DataTypes& DataTypes::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_DataTypes_JTRNSYSMessage_2eproto.base);
  return *internal_default_instance();
}


void DataTypes::Clear() {
// @@protoc_insertion_point(message_clear_start:JTRNSYSDataTypes.DataTypes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  arrays_.Clear();
  stringdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&doubledata_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&intdata_) -
      reinterpret_cast<char*>(&doubledata_)) + sizeof(intdata_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* DataTypes::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<DataTypes*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string stringData = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("JTRNSYSDataTypes.DataTypes.stringData");
        object = msg->mutable_stringdata();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // int32 intData = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_intdata(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // double doubleData = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 25) goto handle_unusual;
        msg->set_doubledata(::google::protobuf::io::UnalignedLoad<double>(ptr));
        ptr += sizeof(double);
        break;
      }
      // repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::JTRNSYSDataTypes::DataTypes_ArrayDataTypes::_InternalParse;
          object = msg->add_arrays();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 34 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool DataTypes::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:JTRNSYSDataTypes.DataTypes)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string stringData = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringdata()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->stringdata().data(), static_cast<int>(this->stringdata().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "JTRNSYSDataTypes.DataTypes.stringData"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 intData = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intdata_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double doubleData = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (25 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &doubledata_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_arrays()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:JTRNSYSDataTypes.DataTypes)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:JTRNSYSDataTypes.DataTypes)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void DataTypes::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:JTRNSYSDataTypes.DataTypes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string stringData = 1;
  if (this->stringdata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringdata().data(), static_cast<int>(this->stringdata().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "JTRNSYSDataTypes.DataTypes.stringData");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->stringdata(), output);
  }

  // int32 intData = 2;
  if (this->intdata() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->intdata(), output);
  }

  // double doubleData = 3;
  if (this->doubledata() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->doubledata(), output);
  }

  // repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->arrays_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->arrays(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:JTRNSYSDataTypes.DataTypes)
}

::google::protobuf::uint8* DataTypes::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:JTRNSYSDataTypes.DataTypes)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string stringData = 1;
  if (this->stringdata().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->stringdata().data(), static_cast<int>(this->stringdata().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "JTRNSYSDataTypes.DataTypes.stringData");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->stringdata(), target);
  }

  // int32 intData = 2;
  if (this->intdata() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->intdata(), target);
  }

  // double doubleData = 3;
  if (this->doubledata() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->doubledata(), target);
  }

  // repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->arrays_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->arrays(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:JTRNSYSDataTypes.DataTypes)
  return target;
}

size_t DataTypes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:JTRNSYSDataTypes.DataTypes)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->arrays_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->arrays(static_cast<int>(i)));
    }
  }

  // string stringData = 1;
  if (this->stringdata().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stringdata());
  }

  // double doubleData = 3;
  if (this->doubledata() != 0) {
    total_size += 1 + 8;
  }

  // int32 intData = 2;
  if (this->intdata() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->intdata());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DataTypes::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:JTRNSYSDataTypes.DataTypes)
  GOOGLE_DCHECK_NE(&from, this);
  const DataTypes* source =
      ::google::protobuf::DynamicCastToGenerated<DataTypes>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:JTRNSYSDataTypes.DataTypes)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:JTRNSYSDataTypes.DataTypes)
    MergeFrom(*source);
  }
}

void DataTypes::MergeFrom(const DataTypes& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:JTRNSYSDataTypes.DataTypes)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  arrays_.MergeFrom(from.arrays_);
  if (from.stringdata().size() > 0) {

    stringdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringdata_);
  }
  if (from.doubledata() != 0) {
    set_doubledata(from.doubledata());
  }
  if (from.intdata() != 0) {
    set_intdata(from.intdata());
  }
}

void DataTypes::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:JTRNSYSDataTypes.DataTypes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DataTypes::CopyFrom(const DataTypes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:JTRNSYSDataTypes.DataTypes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataTypes::IsInitialized() const {
  return true;
}

void DataTypes::Swap(DataTypes* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DataTypes::InternalSwap(DataTypes* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&arrays_)->InternalSwap(CastToBase(&other->arrays_));
  stringdata_.Swap(&other->stringdata_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(doubledata_, other->doubledata_);
  swap(intdata_, other->intdata_);
}

::google::protobuf::Metadata DataTypes::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_JTRNSYSMessage_2eproto);
  return ::file_level_metadata_JTRNSYSMessage_2eproto[kIndexInFileMessages];
}


// ===================================================================

void JTRNSYSData::InitAsDefaultInstance() {
}
class JTRNSYSData::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int JTRNSYSData::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

JTRNSYSData::JTRNSYSData()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:JTRNSYSDataTypes.JTRNSYSData)
}
JTRNSYSData::JTRNSYSData(const JTRNSYSData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:JTRNSYSDataTypes.JTRNSYSData)
}

void JTRNSYSData::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_JTRNSYSData_JTRNSYSMessage_2eproto.base);
}

JTRNSYSData::~JTRNSYSData() {
  // @@protoc_insertion_point(destructor:JTRNSYSDataTypes.JTRNSYSData)
  SharedDtor();
}

void JTRNSYSData::SharedDtor() {
}

void JTRNSYSData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const JTRNSYSData& JTRNSYSData::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_JTRNSYSData_JTRNSYSMessage_2eproto.base);
  return *internal_default_instance();
}


void JTRNSYSData::Clear() {
// @@protoc_insertion_point(message_clear_start:JTRNSYSDataTypes.JTRNSYSData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* JTRNSYSData::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<JTRNSYSData*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated .JTRNSYSDataTypes.DataTypes data = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::JTRNSYSDataTypes::DataTypes::_InternalParse;
          object = msg->add_data();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 10 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool JTRNSYSData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:JTRNSYSDataTypes.JTRNSYSData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .JTRNSYSDataTypes.DataTypes data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:JTRNSYSDataTypes.JTRNSYSData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:JTRNSYSDataTypes.JTRNSYSData)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void JTRNSYSData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:JTRNSYSDataTypes.JTRNSYSData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .JTRNSYSDataTypes.DataTypes data = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->data_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->data(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:JTRNSYSDataTypes.JTRNSYSData)
}

::google::protobuf::uint8* JTRNSYSData::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:JTRNSYSDataTypes.JTRNSYSData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .JTRNSYSDataTypes.DataTypes data = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->data_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->data(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:JTRNSYSDataTypes.JTRNSYSData)
  return target;
}

size_t JTRNSYSData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:JTRNSYSDataTypes.JTRNSYSData)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .JTRNSYSDataTypes.DataTypes data = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->data_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->data(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void JTRNSYSData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:JTRNSYSDataTypes.JTRNSYSData)
  GOOGLE_DCHECK_NE(&from, this);
  const JTRNSYSData* source =
      ::google::protobuf::DynamicCastToGenerated<JTRNSYSData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:JTRNSYSDataTypes.JTRNSYSData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:JTRNSYSDataTypes.JTRNSYSData)
    MergeFrom(*source);
  }
}

void JTRNSYSData::MergeFrom(const JTRNSYSData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:JTRNSYSDataTypes.JTRNSYSData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
}

void JTRNSYSData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:JTRNSYSDataTypes.JTRNSYSData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JTRNSYSData::CopyFrom(const JTRNSYSData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:JTRNSYSDataTypes.JTRNSYSData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JTRNSYSData::IsInitialized() const {
  return true;
}

void JTRNSYSData::Swap(JTRNSYSData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void JTRNSYSData::InternalSwap(JTRNSYSData* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&data_)->InternalSwap(CastToBase(&other->data_));
}

::google::protobuf::Metadata JTRNSYSData::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_JTRNSYSMessage_2eproto);
  return ::file_level_metadata_JTRNSYSMessage_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace JTRNSYSDataTypes
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::JTRNSYSDataTypes::DataTypes_ArrayDataTypes* Arena::CreateMaybeMessage< ::JTRNSYSDataTypes::DataTypes_ArrayDataTypes >(Arena* arena) {
  return Arena::CreateInternal< ::JTRNSYSDataTypes::DataTypes_ArrayDataTypes >(arena);
}
template<> PROTOBUF_NOINLINE ::JTRNSYSDataTypes::DataTypes* Arena::CreateMaybeMessage< ::JTRNSYSDataTypes::DataTypes >(Arena* arena) {
  return Arena::CreateInternal< ::JTRNSYSDataTypes::DataTypes >(arena);
}
template<> PROTOBUF_NOINLINE ::JTRNSYSDataTypes::JTRNSYSData* Arena::CreateMaybeMessage< ::JTRNSYSDataTypes::JTRNSYSData >(Arena* arena) {
  return Arena::CreateInternal< ::JTRNSYSDataTypes::JTRNSYSData >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
