# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JTRNSYSMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='JTRNSYSMessage.proto',
  package='JTRNSYSDataTypes',
  syntax='proto3',
  serialized_options=_b('\n\ncom.socketB\014JTRNSYSProto'),
  serialized_pb=_b('\n\x14JTRNSYSMessage.proto\x12\x10JTRNSYSDataTypes\"\xce\x01\n\tDataTypes\x12\x12\n\nstringData\x18\x01 \x01(\t\x12\x0f\n\x07intData\x18\x02 \x01(\x05\x12\x12\n\ndoubleData\x18\x03 \x01(\x01\x12:\n\x06\x61rrays\x18\x04 \x03(\x0b\x32*.JTRNSYSDataTypes.DataTypes.ArrayDataTypes\x1aL\n\x0e\x41rrayDataTypes\x12\x13\n\x0b\x64oubleArray\x18\x01 \x01(\x01\x12\x10\n\x08intArray\x18\x02 \x01(\x05\x12\x13\n\x0bstringArray\x18\x03 \x01(\t\"8\n\x0bJTRNSYSData\x12)\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1b.JTRNSYSDataTypes.DataTypesB\x1a\n\ncom.socketB\x0cJTRNSYSProtob\x06proto3')
)




_DATATYPES_ARRAYDATATYPES = _descriptor.Descriptor(
  name='ArrayDataTypes',
  full_name='JTRNSYSDataTypes.DataTypes.ArrayDataTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doubleArray', full_name='JTRNSYSDataTypes.DataTypes.ArrayDataTypes.doubleArray', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intArray', full_name='JTRNSYSDataTypes.DataTypes.ArrayDataTypes.intArray', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stringArray', full_name='JTRNSYSDataTypes.DataTypes.ArrayDataTypes.stringArray', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=249,
)

_DATATYPES = _descriptor.Descriptor(
  name='DataTypes',
  full_name='JTRNSYSDataTypes.DataTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stringData', full_name='JTRNSYSDataTypes.DataTypes.stringData', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intData', full_name='JTRNSYSDataTypes.DataTypes.intData', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doubleData', full_name='JTRNSYSDataTypes.DataTypes.doubleData', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrays', full_name='JTRNSYSDataTypes.DataTypes.arrays', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATATYPES_ARRAYDATATYPES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=249,
)


_JTRNSYSDATA = _descriptor.Descriptor(
  name='JTRNSYSData',
  full_name='JTRNSYSDataTypes.JTRNSYSData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='JTRNSYSDataTypes.JTRNSYSData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=307,
)

_DATATYPES_ARRAYDATATYPES.containing_type = _DATATYPES
_DATATYPES.fields_by_name['arrays'].message_type = _DATATYPES_ARRAYDATATYPES
_JTRNSYSDATA.fields_by_name['data'].message_type = _DATATYPES
DESCRIPTOR.message_types_by_name['DataTypes'] = _DATATYPES
DESCRIPTOR.message_types_by_name['JTRNSYSData'] = _JTRNSYSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataTypes = _reflection.GeneratedProtocolMessageType('DataTypes', (_message.Message,), dict(

  ArrayDataTypes = _reflection.GeneratedProtocolMessageType('ArrayDataTypes', (_message.Message,), dict(
    DESCRIPTOR = _DATATYPES_ARRAYDATATYPES,
    __module__ = 'JTRNSYSMessage_pb2'
    # @@protoc_insertion_point(class_scope:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
    ))
  ,
  DESCRIPTOR = _DATATYPES,
  __module__ = 'JTRNSYSMessage_pb2'
  # @@protoc_insertion_point(class_scope:JTRNSYSDataTypes.DataTypes)
  ))
_sym_db.RegisterMessage(DataTypes)
_sym_db.RegisterMessage(DataTypes.ArrayDataTypes)

JTRNSYSData = _reflection.GeneratedProtocolMessageType('JTRNSYSData', (_message.Message,), dict(
  DESCRIPTOR = _JTRNSYSDATA,
  __module__ = 'JTRNSYSMessage_pb2'
  # @@protoc_insertion_point(class_scope:JTRNSYSDataTypes.JTRNSYSData)
  ))
_sym_db.RegisterMessage(JTRNSYSData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
