// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JTRNSYSMessage.proto

package com.socket;

public final class JTRNSYSProto {
  private JTRNSYSProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataTypesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JTRNSYSDataTypes.DataTypes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string stringData = 1;</code>
     */
    java.lang.String getStringData();
    /**
     * <code>string stringData = 1;</code>
     */
    com.google.protobuf.ByteString
        getStringDataBytes();

    /**
     * <code>int32 intData = 2;</code>
     */
    int getIntData();

    /**
     * <code>double doubleData = 3;</code>
     */
    double getDoubleData();

    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    java.util.List<com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes> 
        getArraysList();
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes getArrays(int index);
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    int getArraysCount();
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    java.util.List<? extends com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder> 
        getArraysOrBuilderList();
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder getArraysOrBuilder(
        int index);
  }
  /**
   * <pre>
   * [START messages]
   * </pre>
   *
   * Protobuf type {@code JTRNSYSDataTypes.DataTypes}
   */
  public  static final class DataTypes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JTRNSYSDataTypes.DataTypes)
      DataTypesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataTypes.newBuilder() to construct.
    private DataTypes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataTypes() {
      stringData_ = "";
      arrays_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataTypes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              stringData_ = s;
              break;
            }
            case 16: {

              intData_ = input.readInt32();
              break;
            }
            case 25: {

              doubleData_ = input.readDouble();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                arrays_ = new java.util.ArrayList<com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes>();
                mutable_bitField0_ |= 0x00000008;
              }
              arrays_.add(
                  input.readMessage(com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          arrays_ = java.util.Collections.unmodifiableList(arrays_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.socket.JTRNSYSProto.DataTypes.class, com.socket.JTRNSYSProto.DataTypes.Builder.class);
    }

    public interface ArrayDataTypesOrBuilder extends
        // @@protoc_insertion_point(interface_extends:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>double doubleArray = 1;</code>
       */
      double getDoubleArray();

      /**
       * <code>int32 intArray = 2;</code>
       */
      int getIntArray();

      /**
       * <code>string stringArray = 3;</code>
       */
      java.lang.String getStringArray();
      /**
       * <code>string stringArray = 3;</code>
       */
      com.google.protobuf.ByteString
          getStringArrayBytes();
    }
    /**
     * <pre>
     *defining arrays
     * </pre>
     *
     * Protobuf type {@code JTRNSYSDataTypes.DataTypes.ArrayDataTypes}
     */
    public  static final class ArrayDataTypes extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
        ArrayDataTypesOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ArrayDataTypes.newBuilder() to construct.
      private ArrayDataTypes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ArrayDataTypes() {
        stringArray_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ArrayDataTypes(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {

                doubleArray_ = input.readDouble();
                break;
              }
              case 16: {

                intArray_ = input.readInt32();
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                stringArray_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.class, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder.class);
      }

      public static final int DOUBLEARRAY_FIELD_NUMBER = 1;
      private double doubleArray_;
      /**
       * <code>double doubleArray = 1;</code>
       */
      public double getDoubleArray() {
        return doubleArray_;
      }

      public static final int INTARRAY_FIELD_NUMBER = 2;
      private int intArray_;
      /**
       * <code>int32 intArray = 2;</code>
       */
      public int getIntArray() {
        return intArray_;
      }

      public static final int STRINGARRAY_FIELD_NUMBER = 3;
      private volatile java.lang.Object stringArray_;
      /**
       * <code>string stringArray = 3;</code>
       */
      public java.lang.String getStringArray() {
        java.lang.Object ref = stringArray_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringArray_ = s;
          return s;
        }
      }
      /**
       * <code>string stringArray = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStringArrayBytes() {
        java.lang.Object ref = stringArray_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringArray_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (doubleArray_ != 0D) {
          output.writeDouble(1, doubleArray_);
        }
        if (intArray_ != 0) {
          output.writeInt32(2, intArray_);
        }
        if (!getStringArrayBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, stringArray_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (doubleArray_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, doubleArray_);
        }
        if (intArray_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, intArray_);
        }
        if (!getStringArrayBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, stringArray_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes)) {
          return super.equals(obj);
        }
        com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes other = (com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes) obj;

        if (java.lang.Double.doubleToLongBits(getDoubleArray())
            != java.lang.Double.doubleToLongBits(
                other.getDoubleArray())) return false;
        if (getIntArray()
            != other.getIntArray()) return false;
        if (!getStringArray()
            .equals(other.getStringArray())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DOUBLEARRAY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDoubleArray()));
        hash = (37 * hash) + INTARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getIntArray();
        hash = (37 * hash) + STRINGARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getStringArray().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       *defining arrays
       * </pre>
       *
       * Protobuf type {@code JTRNSYSDataTypes.DataTypes.ArrayDataTypes}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
          com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.class, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder.class);
        }

        // Construct using com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          doubleArray_ = 0D;

          intArray_ = 0;

          stringArray_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_descriptor;
        }

        @java.lang.Override
        public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes getDefaultInstanceForType() {
          return com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.getDefaultInstance();
        }

        @java.lang.Override
        public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes build() {
          com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes buildPartial() {
          com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes result = new com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes(this);
          result.doubleArray_ = doubleArray_;
          result.intArray_ = intArray_;
          result.stringArray_ = stringArray_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes) {
            return mergeFrom((com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes other) {
          if (other == com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.getDefaultInstance()) return this;
          if (other.getDoubleArray() != 0D) {
            setDoubleArray(other.getDoubleArray());
          }
          if (other.getIntArray() != 0) {
            setIntArray(other.getIntArray());
          }
          if (!other.getStringArray().isEmpty()) {
            stringArray_ = other.stringArray_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private double doubleArray_ ;
        /**
         * <code>double doubleArray = 1;</code>
         */
        public double getDoubleArray() {
          return doubleArray_;
        }
        /**
         * <code>double doubleArray = 1;</code>
         */
        public Builder setDoubleArray(double value) {
          
          doubleArray_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double doubleArray = 1;</code>
         */
        public Builder clearDoubleArray() {
          
          doubleArray_ = 0D;
          onChanged();
          return this;
        }

        private int intArray_ ;
        /**
         * <code>int32 intArray = 2;</code>
         */
        public int getIntArray() {
          return intArray_;
        }
        /**
         * <code>int32 intArray = 2;</code>
         */
        public Builder setIntArray(int value) {
          
          intArray_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 intArray = 2;</code>
         */
        public Builder clearIntArray() {
          
          intArray_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object stringArray_ = "";
        /**
         * <code>string stringArray = 3;</code>
         */
        public java.lang.String getStringArray() {
          java.lang.Object ref = stringArray_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            stringArray_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string stringArray = 3;</code>
         */
        public com.google.protobuf.ByteString
            getStringArrayBytes() {
          java.lang.Object ref = stringArray_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            stringArray_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string stringArray = 3;</code>
         */
        public Builder setStringArray(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          stringArray_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string stringArray = 3;</code>
         */
        public Builder clearStringArray() {
          
          stringArray_ = getDefaultInstance().getStringArray();
          onChanged();
          return this;
        }
        /**
         * <code>string stringArray = 3;</code>
         */
        public Builder setStringArrayBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          stringArray_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
      }

      // @@protoc_insertion_point(class_scope:JTRNSYSDataTypes.DataTypes.ArrayDataTypes)
      private static final com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes();
      }

      public static com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ArrayDataTypes>
          PARSER = new com.google.protobuf.AbstractParser<ArrayDataTypes>() {
        @java.lang.Override
        public ArrayDataTypes parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ArrayDataTypes(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ArrayDataTypes> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ArrayDataTypes> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int STRINGDATA_FIELD_NUMBER = 1;
    private volatile java.lang.Object stringData_;
    /**
     * <code>string stringData = 1;</code>
     */
    public java.lang.String getStringData() {
      java.lang.Object ref = stringData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringData_ = s;
        return s;
      }
    }
    /**
     * <code>string stringData = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStringDataBytes() {
      java.lang.Object ref = stringData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INTDATA_FIELD_NUMBER = 2;
    private int intData_;
    /**
     * <code>int32 intData = 2;</code>
     */
    public int getIntData() {
      return intData_;
    }

    public static final int DOUBLEDATA_FIELD_NUMBER = 3;
    private double doubleData_;
    /**
     * <code>double doubleData = 3;</code>
     */
    public double getDoubleData() {
      return doubleData_;
    }

    public static final int ARRAYS_FIELD_NUMBER = 4;
    private java.util.List<com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes> arrays_;
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    public java.util.List<com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes> getArraysList() {
      return arrays_;
    }
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    public java.util.List<? extends com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder> 
        getArraysOrBuilderList() {
      return arrays_;
    }
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    public int getArraysCount() {
      return arrays_.size();
    }
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes getArrays(int index) {
      return arrays_.get(index);
    }
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
     */
    public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder getArraysOrBuilder(
        int index) {
      return arrays_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStringDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stringData_);
      }
      if (intData_ != 0) {
        output.writeInt32(2, intData_);
      }
      if (doubleData_ != 0D) {
        output.writeDouble(3, doubleData_);
      }
      for (int i = 0; i < arrays_.size(); i++) {
        output.writeMessage(4, arrays_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStringDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stringData_);
      }
      if (intData_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, intData_);
      }
      if (doubleData_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, doubleData_);
      }
      for (int i = 0; i < arrays_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, arrays_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.socket.JTRNSYSProto.DataTypes)) {
        return super.equals(obj);
      }
      com.socket.JTRNSYSProto.DataTypes other = (com.socket.JTRNSYSProto.DataTypes) obj;

      if (!getStringData()
          .equals(other.getStringData())) return false;
      if (getIntData()
          != other.getIntData()) return false;
      if (java.lang.Double.doubleToLongBits(getDoubleData())
          != java.lang.Double.doubleToLongBits(
              other.getDoubleData())) return false;
      if (!getArraysList()
          .equals(other.getArraysList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STRINGDATA_FIELD_NUMBER;
      hash = (53 * hash) + getStringData().hashCode();
      hash = (37 * hash) + INTDATA_FIELD_NUMBER;
      hash = (53 * hash) + getIntData();
      hash = (37 * hash) + DOUBLEDATA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getDoubleData()));
      if (getArraysCount() > 0) {
        hash = (37 * hash) + ARRAYS_FIELD_NUMBER;
        hash = (53 * hash) + getArraysList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.socket.JTRNSYSProto.DataTypes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.socket.JTRNSYSProto.DataTypes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.socket.JTRNSYSProto.DataTypes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * [START messages]
     * </pre>
     *
     * Protobuf type {@code JTRNSYSDataTypes.DataTypes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JTRNSYSDataTypes.DataTypes)
        com.socket.JTRNSYSProto.DataTypesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.socket.JTRNSYSProto.DataTypes.class, com.socket.JTRNSYSProto.DataTypes.Builder.class);
      }

      // Construct using com.socket.JTRNSYSProto.DataTypes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArraysFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        stringData_ = "";

        intData_ = 0;

        doubleData_ = 0D;

        if (arraysBuilder_ == null) {
          arrays_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          arraysBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_DataTypes_descriptor;
      }

      @java.lang.Override
      public com.socket.JTRNSYSProto.DataTypes getDefaultInstanceForType() {
        return com.socket.JTRNSYSProto.DataTypes.getDefaultInstance();
      }

      @java.lang.Override
      public com.socket.JTRNSYSProto.DataTypes build() {
        com.socket.JTRNSYSProto.DataTypes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.socket.JTRNSYSProto.DataTypes buildPartial() {
        com.socket.JTRNSYSProto.DataTypes result = new com.socket.JTRNSYSProto.DataTypes(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.stringData_ = stringData_;
        result.intData_ = intData_;
        result.doubleData_ = doubleData_;
        if (arraysBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            arrays_ = java.util.Collections.unmodifiableList(arrays_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.arrays_ = arrays_;
        } else {
          result.arrays_ = arraysBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socket.JTRNSYSProto.DataTypes) {
          return mergeFrom((com.socket.JTRNSYSProto.DataTypes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.socket.JTRNSYSProto.DataTypes other) {
        if (other == com.socket.JTRNSYSProto.DataTypes.getDefaultInstance()) return this;
        if (!other.getStringData().isEmpty()) {
          stringData_ = other.stringData_;
          onChanged();
        }
        if (other.getIntData() != 0) {
          setIntData(other.getIntData());
        }
        if (other.getDoubleData() != 0D) {
          setDoubleData(other.getDoubleData());
        }
        if (arraysBuilder_ == null) {
          if (!other.arrays_.isEmpty()) {
            if (arrays_.isEmpty()) {
              arrays_ = other.arrays_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureArraysIsMutable();
              arrays_.addAll(other.arrays_);
            }
            onChanged();
          }
        } else {
          if (!other.arrays_.isEmpty()) {
            if (arraysBuilder_.isEmpty()) {
              arraysBuilder_.dispose();
              arraysBuilder_ = null;
              arrays_ = other.arrays_;
              bitField0_ = (bitField0_ & ~0x00000008);
              arraysBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArraysFieldBuilder() : null;
            } else {
              arraysBuilder_.addAllMessages(other.arrays_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.socket.JTRNSYSProto.DataTypes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.socket.JTRNSYSProto.DataTypes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object stringData_ = "";
      /**
       * <code>string stringData = 1;</code>
       */
      public java.lang.String getStringData() {
        java.lang.Object ref = stringData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringData = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStringDataBytes() {
        java.lang.Object ref = stringData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringData = 1;</code>
       */
      public Builder setStringData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringData = 1;</code>
       */
      public Builder clearStringData() {
        
        stringData_ = getDefaultInstance().getStringData();
        onChanged();
        return this;
      }
      /**
       * <code>string stringData = 1;</code>
       */
      public Builder setStringDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringData_ = value;
        onChanged();
        return this;
      }

      private int intData_ ;
      /**
       * <code>int32 intData = 2;</code>
       */
      public int getIntData() {
        return intData_;
      }
      /**
       * <code>int32 intData = 2;</code>
       */
      public Builder setIntData(int value) {
        
        intData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 intData = 2;</code>
       */
      public Builder clearIntData() {
        
        intData_ = 0;
        onChanged();
        return this;
      }

      private double doubleData_ ;
      /**
       * <code>double doubleData = 3;</code>
       */
      public double getDoubleData() {
        return doubleData_;
      }
      /**
       * <code>double doubleData = 3;</code>
       */
      public Builder setDoubleData(double value) {
        
        doubleData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double doubleData = 3;</code>
       */
      public Builder clearDoubleData() {
        
        doubleData_ = 0D;
        onChanged();
        return this;
      }

      private java.util.List<com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes> arrays_ =
        java.util.Collections.emptyList();
      private void ensureArraysIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          arrays_ = new java.util.ArrayList<com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes>(arrays_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder> arraysBuilder_;

      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public java.util.List<com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes> getArraysList() {
        if (arraysBuilder_ == null) {
          return java.util.Collections.unmodifiableList(arrays_);
        } else {
          return arraysBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public int getArraysCount() {
        if (arraysBuilder_ == null) {
          return arrays_.size();
        } else {
          return arraysBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes getArrays(int index) {
        if (arraysBuilder_ == null) {
          return arrays_.get(index);
        } else {
          return arraysBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder setArrays(
          int index, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes value) {
        if (arraysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArraysIsMutable();
          arrays_.set(index, value);
          onChanged();
        } else {
          arraysBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder setArrays(
          int index, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder builderForValue) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          arrays_.set(index, builderForValue.build());
          onChanged();
        } else {
          arraysBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder addArrays(com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes value) {
        if (arraysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArraysIsMutable();
          arrays_.add(value);
          onChanged();
        } else {
          arraysBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder addArrays(
          int index, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes value) {
        if (arraysBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArraysIsMutable();
          arrays_.add(index, value);
          onChanged();
        } else {
          arraysBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder addArrays(
          com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder builderForValue) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          arrays_.add(builderForValue.build());
          onChanged();
        } else {
          arraysBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder addArrays(
          int index, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder builderForValue) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          arrays_.add(index, builderForValue.build());
          onChanged();
        } else {
          arraysBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder addAllArrays(
          java.lang.Iterable<? extends com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes> values) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, arrays_);
          onChanged();
        } else {
          arraysBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder clearArrays() {
        if (arraysBuilder_ == null) {
          arrays_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          arraysBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public Builder removeArrays(int index) {
        if (arraysBuilder_ == null) {
          ensureArraysIsMutable();
          arrays_.remove(index);
          onChanged();
        } else {
          arraysBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder getArraysBuilder(
          int index) {
        return getArraysFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder getArraysOrBuilder(
          int index) {
        if (arraysBuilder_ == null) {
          return arrays_.get(index);  } else {
          return arraysBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public java.util.List<? extends com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder> 
           getArraysOrBuilderList() {
        if (arraysBuilder_ != null) {
          return arraysBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(arrays_);
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder addArraysBuilder() {
        return getArraysFieldBuilder().addBuilder(
            com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.getDefaultInstance());
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder addArraysBuilder(
          int index) {
        return getArraysFieldBuilder().addBuilder(
            index, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.getDefaultInstance());
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes.ArrayDataTypes arrays = 4;</code>
       */
      public java.util.List<com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder> 
           getArraysBuilderList() {
        return getArraysFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder> 
          getArraysFieldBuilder() {
        if (arraysBuilder_ == null) {
          arraysBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypes.Builder, com.socket.JTRNSYSProto.DataTypes.ArrayDataTypesOrBuilder>(
                  arrays_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          arrays_ = null;
        }
        return arraysBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JTRNSYSDataTypes.DataTypes)
    }

    // @@protoc_insertion_point(class_scope:JTRNSYSDataTypes.DataTypes)
    private static final com.socket.JTRNSYSProto.DataTypes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.socket.JTRNSYSProto.DataTypes();
    }

    public static com.socket.JTRNSYSProto.DataTypes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataTypes>
        PARSER = new com.google.protobuf.AbstractParser<DataTypes>() {
      @java.lang.Override
      public DataTypes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataTypes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataTypes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataTypes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.socket.JTRNSYSProto.DataTypes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface JTRNSYSDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:JTRNSYSDataTypes.JTRNSYSData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    java.util.List<com.socket.JTRNSYSProto.DataTypes> 
        getDataList();
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    com.socket.JTRNSYSProto.DataTypes getData(int index);
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    java.util.List<? extends com.socket.JTRNSYSProto.DataTypesOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    com.socket.JTRNSYSProto.DataTypesOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Our data is just one of these.
   * </pre>
   *
   * Protobuf type {@code JTRNSYSDataTypes.JTRNSYSData}
   */
  public  static final class JTRNSYSData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:JTRNSYSDataTypes.JTRNSYSData)
      JTRNSYSDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use JTRNSYSData.newBuilder() to construct.
    private JTRNSYSData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private JTRNSYSData() {
      data_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private JTRNSYSData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                data_ = new java.util.ArrayList<com.socket.JTRNSYSProto.DataTypes>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(
                  input.readMessage(com.socket.JTRNSYSProto.DataTypes.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_JTRNSYSData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_JTRNSYSData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.socket.JTRNSYSProto.JTRNSYSData.class, com.socket.JTRNSYSProto.JTRNSYSData.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<com.socket.JTRNSYSProto.DataTypes> data_;
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    public java.util.List<com.socket.JTRNSYSProto.DataTypes> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    public java.util.List<? extends com.socket.JTRNSYSProto.DataTypesOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    public com.socket.JTRNSYSProto.DataTypes getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
     */
    public com.socket.JTRNSYSProto.DataTypesOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.socket.JTRNSYSProto.JTRNSYSData)) {
        return super.equals(obj);
      }
      com.socket.JTRNSYSProto.JTRNSYSData other = (com.socket.JTRNSYSProto.JTRNSYSData) obj;

      if (!getDataList()
          .equals(other.getDataList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDataCount() > 0) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.socket.JTRNSYSProto.JTRNSYSData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.socket.JTRNSYSProto.JTRNSYSData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Our data is just one of these.
     * </pre>
     *
     * Protobuf type {@code JTRNSYSDataTypes.JTRNSYSData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:JTRNSYSDataTypes.JTRNSYSData)
        com.socket.JTRNSYSProto.JTRNSYSDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_JTRNSYSData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_JTRNSYSData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.socket.JTRNSYSProto.JTRNSYSData.class, com.socket.JTRNSYSProto.JTRNSYSData.Builder.class);
      }

      // Construct using com.socket.JTRNSYSProto.JTRNSYSData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.socket.JTRNSYSProto.internal_static_JTRNSYSDataTypes_JTRNSYSData_descriptor;
      }

      @java.lang.Override
      public com.socket.JTRNSYSProto.JTRNSYSData getDefaultInstanceForType() {
        return com.socket.JTRNSYSProto.JTRNSYSData.getDefaultInstance();
      }

      @java.lang.Override
      public com.socket.JTRNSYSProto.JTRNSYSData build() {
        com.socket.JTRNSYSProto.JTRNSYSData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.socket.JTRNSYSProto.JTRNSYSData buildPartial() {
        com.socket.JTRNSYSProto.JTRNSYSData result = new com.socket.JTRNSYSProto.JTRNSYSData(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.socket.JTRNSYSProto.JTRNSYSData) {
          return mergeFrom((com.socket.JTRNSYSProto.JTRNSYSData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.socket.JTRNSYSProto.JTRNSYSData other) {
        if (other == com.socket.JTRNSYSProto.JTRNSYSData.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.socket.JTRNSYSProto.JTRNSYSData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.socket.JTRNSYSProto.JTRNSYSData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.socket.JTRNSYSProto.DataTypes> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          data_ = new java.util.ArrayList<com.socket.JTRNSYSProto.DataTypes>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.socket.JTRNSYSProto.DataTypes, com.socket.JTRNSYSProto.DataTypes.Builder, com.socket.JTRNSYSProto.DataTypesOrBuilder> dataBuilder_;

      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public java.util.List<com.socket.JTRNSYSProto.DataTypes> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder setData(
          int index, com.socket.JTRNSYSProto.DataTypes value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder setData(
          int index, com.socket.JTRNSYSProto.DataTypes.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder addData(com.socket.JTRNSYSProto.DataTypes value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder addData(
          int index, com.socket.JTRNSYSProto.DataTypes value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder addData(
          com.socket.JTRNSYSProto.DataTypes.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder addData(
          int index, com.socket.JTRNSYSProto.DataTypes.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.socket.JTRNSYSProto.DataTypes> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public com.socket.JTRNSYSProto.DataTypesOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public java.util.List<? extends com.socket.JTRNSYSProto.DataTypesOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            com.socket.JTRNSYSProto.DataTypes.getDefaultInstance());
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public com.socket.JTRNSYSProto.DataTypes.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, com.socket.JTRNSYSProto.DataTypes.getDefaultInstance());
      }
      /**
       * <code>repeated .JTRNSYSDataTypes.DataTypes data = 1;</code>
       */
      public java.util.List<com.socket.JTRNSYSProto.DataTypes.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.socket.JTRNSYSProto.DataTypes, com.socket.JTRNSYSProto.DataTypes.Builder, com.socket.JTRNSYSProto.DataTypesOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.socket.JTRNSYSProto.DataTypes, com.socket.JTRNSYSProto.DataTypes.Builder, com.socket.JTRNSYSProto.DataTypesOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:JTRNSYSDataTypes.JTRNSYSData)
    }

    // @@protoc_insertion_point(class_scope:JTRNSYSDataTypes.JTRNSYSData)
    private static final com.socket.JTRNSYSProto.JTRNSYSData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.socket.JTRNSYSProto.JTRNSYSData();
    }

    public static com.socket.JTRNSYSProto.JTRNSYSData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<JTRNSYSData>
        PARSER = new com.google.protobuf.AbstractParser<JTRNSYSData>() {
      @java.lang.Override
      public JTRNSYSData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JTRNSYSData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<JTRNSYSData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<JTRNSYSData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.socket.JTRNSYSProto.JTRNSYSData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JTRNSYSDataTypes_DataTypes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JTRNSYSDataTypes_DataTypes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_JTRNSYSDataTypes_JTRNSYSData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_JTRNSYSDataTypes_JTRNSYSData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024JTRNSYSMessage.proto\022\020JTRNSYSDataTypes" +
      "\"\316\001\n\tDataTypes\022\022\n\nstringData\030\001 \001(\t\022\017\n\007in" +
      "tData\030\002 \001(\005\022\022\n\ndoubleData\030\003 \001(\001\022:\n\006array" +
      "s\030\004 \003(\0132*.JTRNSYSDataTypes.DataTypes.Arr" +
      "ayDataTypes\032L\n\016ArrayDataTypes\022\023\n\013doubleA" +
      "rray\030\001 \001(\001\022\020\n\010intArray\030\002 \001(\005\022\023\n\013stringAr" +
      "ray\030\003 \001(\t\"8\n\013JTRNSYSData\022)\n\004data\030\001 \003(\0132\033" +
      ".JTRNSYSDataTypes.DataTypesB\032\n\ncom.socke" +
      "tB\014JTRNSYSProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_JTRNSYSDataTypes_DataTypes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_JTRNSYSDataTypes_DataTypes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JTRNSYSDataTypes_DataTypes_descriptor,
        new java.lang.String[] { "StringData", "IntData", "DoubleData", "Arrays", });
    internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_descriptor =
      internal_static_JTRNSYSDataTypes_DataTypes_descriptor.getNestedTypes().get(0);
    internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JTRNSYSDataTypes_DataTypes_ArrayDataTypes_descriptor,
        new java.lang.String[] { "DoubleArray", "IntArray", "StringArray", });
    internal_static_JTRNSYSDataTypes_JTRNSYSData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_JTRNSYSDataTypes_JTRNSYSData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_JTRNSYSDataTypes_JTRNSYSData_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
